#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/interactive"

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_int_pre" -exec source {} \;

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_int" -exec source {} \;

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_int_post" -exec source {} \;
