#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/interactive"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_int_pre"  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_int"  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_int_post"  )" pv

