#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/interactive"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_int_pre")" 

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_int"  )"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_int_post"  )"
