#!/bin/bash

source interactive

find ../user_scripts/ -name "*bash_int_pre" | xargs -0 source

find ../user_scripts/ -name "*bash_int" | xargs -0 source

find ../user_scripts/ -name "*bash_int_post" | xargs -0 source
