#!/bin/bash

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_int_pre" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  )"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_int" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  )"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_int_post" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  )"
