#!/bin/bash

find ../user_scripts/ \( -name "*_int_pre" \
    -and -not -name "*zsh*" -and -not "*bash*" \
    -and -not -name "*csh*" -and -not "*fish*" \) | xargs -0 source

find ../user_scripts/ \( -name "*_int" \
    -and -not -name "*zsh*" -and -not "*bash*" \
    -and -not -name "*csh*" -and -not "*fish*" \) | xargs -0 source

find ../user_scripts/ \( -name "*_int_post" \
    -and -not -name "*zsh*" -and -not "*bash*" \
    -and -not -name "*csh*" -and -not "*fish*" \) | xargs -0 source
