#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/interactive"

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_int_pre"  \
    | while read -r file; do
	echo "$file"
        source "$file"
    done

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_int"  \
    | while read -r file; do
        source "$file"
    done

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_int_post"  \
    | while read -r file; do
        source "$file"
    done
