#!/bin/bash

source login

find ../user_scripts/ -name "*bash_login_pre" | xargs -0 source

find ../user_scripts/ -name "*bash_login" | xargs -0 source

find ../user_scripts/ -name "*bash_login_post" | xargs -0 source
