#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/login"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_login_pre"  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_login"  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_login_post"  )" pv
