#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/login"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_login_pre"  )"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_login"  )"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_login_post"  )"
