#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/login"

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_login_pre"  \
    | while read -r file; do
        source "$file"
    done

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_login"  \
    | while read -r file; do
        source "$file"
    done

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_login_post"  \
    | while read -r file; do
        source "$file"
    done
