#!/bin/bash

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_login_pre" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  -print ); do
    source "$file"
done

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_login" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  -print ); do
    source "$file"
done

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_login_post" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  -print ); do
    source "$file"
done
