#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/login"

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_login_pre"  -print ); do
    source "$file"
done

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_login"  -print ); do
    source "$file"
done

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_login_post"  -print ); do
    source "$file"
done
