#!/bin/bash


for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_logout_pre" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  -print ); do
    source "$file"
done 

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_logout" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  -print ); do
    source "$file"
done 

for file in $(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_logout_post" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  -print ); do
    source "$file"
done 
