#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/logout"

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_logout_pre"  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_logout"  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" -name "*zsh_logout_post"  )" pv
