#!/bin/bash

source "$SCRIPT_DIRECTORY/sys_scripts/logout"

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_logout_pre" -exec source {} \;

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_logout" -exec source {} \;

find "$SCRIPT_DIRECTORY/user_scripts/" -name "*bash_logout_post" -exec source {} \;
