#!/bin/bash

source logout

find ../user_scripts/ -name "*bash_logout_pre" | xargs -0 source

find ../user_scripts/ -name "*bash_logout" | xargs -0 source

find ../user_scripts/ -name "*bash_logout_post" | xargs -0 source
