#!/bin/bash


while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_logout_pre" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_logout" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  )" pv

while read file; do
    source "$file"
done <<< "$(find "$SCRIPT_DIRECTORY/user_scripts/" \( -name "*_logout_post" \
    -and -not -name "*zsh*" -and -not -name "*bash*" \
    -and -not -name "*csh*" -and -not -name "*fish*" \)  )" pv
