#!/bin/bash
for file in $(find "$HOME/.ssh" -type f \( -not -name "*known_hosts*" \
        -and -not -name "*pub" -and -not -name "*config*" -and -not -name "agent.env" \
        -and -not -name ".agent-environment" \) -print ); do
    ssh-add "$file"
done
