#!/bin/bash

add_ssh_keys() {
    find "$HOME/.ssh" -type f \( -not -name "*known_hosts*" -and -not -name "*pub" \
        -and -not -name "*config*" -and -not -name ".agent-environment" \) \
        -exec ssh-add {} \;
}

add_ssh_keys
