#!/bin/bash

SSH_ENV="$HOME/.ssh/.agent-environment"

mkdir "$HOME/.ssh" >> /dev/null 2>&1 

function start_agent {
    createNewAgent=false

    if [ -f "$SSH_ENV" ]; then
        . "$SSH_ENV" > /dev/null 2>&1

        pgrep ssh-agent | grep "$SSH_AGENT_PID" > /dev/null 2>&1 || {
            createNewAgent=true;
        }
    else
        createNewAgent=true;
    fi

    if [[ $createNewAgent = true ]]; then
        ssh-agent | sed 's/^echo/#echo/' > "$SSH_ENV"
        chmod 600 "$SSH_ENV"
        . "$SSH_ENV" > /dev/null 2>&1
    fi
}

start_agent
